# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Philipp Nazari
title: Mathematics and Machine Learning at ETH Zurich
email: pnazari [at] student.ethz.ch
website:

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: philna00
github_username: phnazari
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username:
linkedin_username: philipp-nazari-941623252
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username:
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently pursuing a masters's degree in mathematics, focussing on Machine Learning, at ETH Zurich.

  My interests include -- in no particular order -- <mark>Geometric Deep Learning</mark> <mark>Differential Geometry</mark> <mark>Representation Learning</mark>.

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Geometric Autoencoders -- What You See is What You Decode
        link: https://proceedings.mlr.press/v202/nazari23a.html
        link_text: Paper [PDF]
        caption: ICML 2023
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/phnazari/GeometricAutoencoder
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Why do Neural Networks Generalize?
        description: Master thesis in the lab of Prof. Bölcskei at ETH Zurich.
      - layout: left
        title: Geometric Encoder Regularization in Autoencoders
        link: https://github.com/phnazari/GeometricEncoderRegularization/blob/master/paper.pdf
        link_text: Paper [PDF]
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/phnazari/GeometricEncoderRegularization
        description: Semester Project at ETH Zurich in the lab of Prof. Thomas Hofmann.
      - layout: left
        title: Entropy Aware Message Passing in Graph Neural Networks
        link: https://arxiv.org/abs/2403.04636
        link_text: Paper [PDF]
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/oliver-lemke/entropy_aware_message_passing
        description: Course work for the Deep Learning course at ETH Zurich by Prof. Thomas Hofmann.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IWR Heidelberg
        link: https://sciai-lab.org/
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: August 2022 - April 2023
        description: |

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ETH Zürich
        caption: 2023-2025
        sub_title: MSc Mathematics
        quote: >
          
        description: | # this will include new lines to allow paragraphs

    
      - layout: left
        title: Ruprecht-Karls-University Heidelberg
        caption: 2019 - 2023
        sub_title: BSc Mathematics
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <b>Courses Taken include:</b> Differential Geometry, Fundamentals of Machine Learning, Lie Groups and Representation Theory,  Matrix Groups, Functional Analysis, Complex Analysis, Prime Numbers and Cryptography.

      - layout: left
        title: Ruprecht-Karls-University Heidelberg
        caption: 2019 - 2022
        sub_title: BSc Physics
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <b>Courses Taken include</b>: Theoretical Statistical Physics, Quantum Mechanics, Particle Physics.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
