# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Philipp Nazari
title: BsC Mathematics Student
email: philipp.nazari [at] stud.uni-heidelberg.de
website: https://www.phnazari.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username:
github_username:  phnazari
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username:
linkedin_username: philipp-nazari-941623252
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username:
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Currently a bachelor student in the field of mathematics at Ruprecht-Karls-University Heidelberg (Germany).

  My interesets include -- in no particular order -- <mark>Geometric Machine Learning</mark> <mark>Differential Geometry</mark> <mark>Autoencoder</mark> <mark>Dynamical Billiards Systems</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IWR Heidelberg
        link: typo.iwr.uni-heidelberg.de/home/
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: August 2022 - April 2023
        description: |
          At the invitation of Prof. Dr. Fred Hamprecht, I stayed at his research group to write a paper about the Geometric Autoencoder. Co-authored by Sebastian Damrich and Fred Hamprecht.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ruprecht-Karls-University Heidelberg
        caption: 2019 - 2023
        sub_title: BSc Mathematics
        quote: >
          GPA of 1.5
        description: | # this will include new lines to allow paragraphs
          Whilst studying physics I realized that I am at least as enthusiastic about the elegance of pure mathematics as I am about the natural beauty of physics. This is why I decided to obtain a second bachelor.
          My main focus lies on Differential Geometry and Mathematical Machine Learning.

          <b>Courses Taken include:</b> Differential Geometry, Fundamentals of Machine Learning, Lie Groups and Representation Theory,  Matrix Groups, Functional Analysis, Complex Analysis, Prime Numbers and Cryptography.

      - layout: left
        title: Ruprecht-Karls-University Heidelberg
        caption: 2019 - 2022
        sub_title: BSc Physics
        quote: >
          GPA of 1.3
        description: | # this will include new lines to allow paragraphs
          Considered one of the leading undergraduate physics courses in germany, I finished the BsC Physics with a GPA of 1.3. My focus lies on theoretical and computational physics.

          <b>Courses Taken include</b>: Theoretical Statistical Physics, Quantum Mechanics, Particle Physics.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Numerical Inverse Magnetic Billiards (Bachelor Thesis in Mathematics)
        link: github.com/phnazari/InverseMagneticBilliards
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/phnazari/InverseMagneticBilliards
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Bachelor Thesis in Mathematics, on "Inverse Magnetic Billiard" systems introduced by Sean Gasiorek. Supervisor: Prof. Dr. Peter Albers.
        description: | # this will include new lines to allow paragraphs
          Finding periodic orbits of inverse magnetic billiard systems in arbitrary convex domains can become an arbitrarily hard problem to solve. By applying techniques from machine learning I propose a numerical approach that to find approximately periodic orbits.

      - layout: top-middle
        title: Geometric Autoencoders (Bachelor Thesis in Physics)
        link: github.com/phnazari/GeometricAutoencoder
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/phnazari/GeometricAutoencoder
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Bachelor Thesis in Physics, in the field of Geometric Machine Learning. Supervisor: Prof. Dr. Fred Hamprecht.
        description: | # this will include new lines to allow paragraphs
          Visualization is a crucial step in exploratory data analysis. One possible approach is to train an autoencoder with low-dimensional latent space. Large network depth and width can help unfolding the data. However, such expressive networks can achieve low reconstruction error even when the latent representation is distorted. To avoid such misleading visualizations, this work proposes first a differential geometric perspective on the decoder, leading to insightful diagnostics for an embedding's distortion, and second a new regularizer mitigating such distortion. The ``Geometric Autoencoder'' avoids stretching the embedding spuriously, so that the visualization captures the data structure more faithfully. It also flags areas where little distortion could not be achieved, thus guarding against misinterpretation. 

      - layout: top-middle
        title: Science Young to Young (4EU+)
        link: https://4euplus.eu/4EU-33.html
        # link_text: Project Website
        quote: >
          A 4EU+ initiative in cooperation of Heidelberg University, Sorbonne University and Milano University. Granted by the European Commission.
        description: | # this will include new lines to allow paragraphs
          Representative of Heidelberg University in a joined 4EU+ project with the goal of creating a educational video on "Machine Learning in Physics".

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
